### ISSUE TITLE
Add the ability of dont ask for file name

### ISSUE THREAD

**Issue by TheElegantCoding** [fredjeck/fav#26]
When i add a new favorite, always ask for a name, i want to add without a name

**Comment by fredjeck** [comment]
Hi and thanks for your feature request. 
This is working by design - goal is to give the opportunity to the user to alias favs upon addition, this is particularly useful when adding multiple instances of the same file. I.e. you are fav'ing the same file upon various environments you can immediately alias the file.
Also this is not a big deal if you dont want to alias the file, pressing enter will accept the default file name.
