### ISSUE TITLE
multiple favorites.json for multiple projects

### ISSUE THREAD

**Issue by FrankS666** [fredjeck/fav#28]
Good extension for vscode. 
Why is the favorites.json stored in a fixed path with fixed name?
Normally we have multiple projects, and we need different favorites.json. If the user can assign a json, the projects would not affect each other.

**Comment by fredjeck** [comment]
Hi, fav has been design around the concept of being  project agnostic, goal was and still is to allow quick access to files which you often need to open, your bash or powershell profile, some configuration or logfile on a remote server etc.
favorites.json is more of a storage rather than a project configuration file.
